services:
  db: 
    container_name: zinois-db
    image: postgres:16.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zinois-db
    restart: always
    ports:
      - "5432:5432"